### ISSUE TITLE
STAC product catalog | short example of querying

### ISSUE THREAD

**Issue by Slegersj** [eu-cdse/documentation#101]
**Current**
[Querying STAC catalog](https://documentation.dataspace.copernicus.eu/APIs/STAC.html#querying-the-catalog:~:text=basic%20product%20search.-,Querying%20the%20catalog,-To%20query%20the)

There is no example mentioned of querying the STAC catalog.

**Reference user ticket**
Zendesk: 108 = Jira CF: DAS-402

**Request**
Include a short example of querying in the "Querying the catalog" section of the documentation.

**Comment by bertcoerver** [comment]
Any progress on this? I'm trying to use the STAC, but keep getting a 405 response ("Method not allowed") doing for example (in Python):

```
params =  {
'collections': ['SENTINEL-2'],
 'limit': 10,
 'bbox': [30.7, 29.4, 31.0, 29.7],
 'datetime': '2023-03-01T00:00:00Z/2023-03-05T23:59:59Z',
}
search_url = 'https://catalogue.dataspace.copernicus.eu/stac/search'
query = r.post(search, json=params).json()
```

So would be happy to see an example.
