### ISSUE TITLE
Impossible to use PyStac client for searching

### ISSUE THREAD

**Issue by chiarch84** [eu-cdse/documentation#132]
The main catalog page doesn't expose any search link and so PySTAC client is not able to perform even a simple query.
The following code returns: "NotImplementedError: No link with rel=search could be found in this catalog"

```
from pystac_client import Client
cat = Client.open("https://datahub.creodias.eu/stac/")
query = cat.search(
    method="POST",
    max_items=None,
    limit=100,
    ids=None,
    collections=["SENTINEL-2"],
    bbox=None,
    intersects=None,
    datetime=None,
    query={"productType": {"eq": "S2MSI1C"}},
    filter=None,
    filter_lang=None,
    sortby=None,
    fields=None,
)
```

More over the conformance classes say that APIs are conformant to https://api.stacspec.org/v1.0.0-rc.1/item-search but if I try to use the method it tells me "Unknown parameter names: ['query']". While in the specs this parameter is previewed.

```
query = ItemSearch(
    url="https://datahub.creodias.eu/stac/search",
    method='GET',
    max_items=None,
    limit=100,
    ids=None,
    collections=["SENTINEL-2"],
    bbox=None,
    intersects=None,
    datetime=None,
    query={"productType": {"eq": "S2MSI1C"}},
    filter=None,
    filter_lang=None,
    sortby=None,
    fields=None,
)
```

**Comment by Pratichhya** [comment]
Hi @chiarch84 , could you also please create a ticket for it here https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new. for this issue so that we can keep track of necessary implementation in the service and updates for the documentation. Thank you.

**Comment by Pratichhya** [comment]
A ticket is raised by @chiarch84 in the helpdesk and handled by the concerned team

**Comment by Pratichhya** [comment]
@KanerLev do you have any update on this topic? I assume it might have been solved in the tickets, could you please help us here with the updates?
