### ISSUE TITLE
openEO docs to add

### ISSUE THREAD

**Issue by jdries** [eu-cdse/documentation#172]
An overview of openEO pages to add to the documentation one by one. Preferably we put them in openeo-community-samples as jupyter notebooks.

- [x] Dynamic land cover mapping: https://github.com/openEOPlatform/sample-notebooks/blob/main/Dynamic%20land%20cover%20mapping.ipynb
- [x] Large scale processing: https://github.com/openEOPlatform/documentation/blob/main/usecases/large-scale-processing/index.md
- [x] Sentinel-3, existing but minimal sample: https://github.com/openEOPlatform/sample-notebooks/blob/main/sentinel-3.ipynb
- [x] #401
- [x] FuseTS: whittakker smoothing

**Comment by Pratichhya** [comment]
@jdries, sorry for getting late with this task and repetitive question. Could you please help me to clarify(keep a note) that for Large-scale processing usecase:

- we want to show how to use the `MultiBackendJobManager` feature 
- give a description solution for Copernicus backend in the validation task(https://github.com/openEOPlatform/openeo-classification/blob/main/notebooks/validation.ipynb)

**Comment by jdries** [comment]
For large scale processing, we can do a copy paste of that page in a PR.
Replace links where possible, no need to mention the validation part. 

The job manager itself also needs a bit better documentation, we could consider a community sample notebook for that.

**Comment by jdries** [comment]
for job manager notebook, perhaps we should consider the sample extraction use case. Maybe doing best available pixel for sentinel-2, and then extracting samples for that over a full country or so.

We have a lot of code for that already, so would need to set something up to gather everything into a high quality example.

**Comment by Pratichhya** [comment]
> for job manager notebook, perhaps we should consider the sample extraction use case. Maybe doing best available pixel for sentinel-2, and then extracting samples for that over a full country or so.
> 
> We have a lot of code for that already, so would need to set something up to gather everything into a high quality example.

Sure an issue is created to work on it #395  😃

**Comment by Pratichhya** [comment]
First version of all the above mentioned examples are added.
