### ISSUE TITLE
S2 L2A and S1 SCL will not be available on KO+7M

### ISSUE THREAD

**Issue by JanssenBrm** [eu-cdse/documentation#177]
Based on the GAP list discussed in the project consortium, the full archive of the S1 L1C and S2 L2A is not yet available starting from KO+7M. We should adapt the documentation accordingly.

**Comment by JanssenBrm** [comment]
@skulis1997  - Is it possible to update the documentation accordingly? We don't want to give the wrong information towards our users.

**Comment by JanssenBrm** [comment]
This issue relates to the information that is shown on the following pages:

- https://documentation.dataspace.copernicus.eu/Data/Sentinel1.html
- https://documentation.dataspace.copernicus.eu/Data/Sentinel2.html

The information on this page is being generated based on the `collections.json` metadata file, specifically the `DataAvailability` part. For example, the S2 TOC information is available at:

https://github.com/eu-cdse/documentation/blob/publish/Data/collections.json#L530

**Comment by Slegersj** [comment]
The data availability documentation pages have been reviewed and updated several times, so we assume we can now close this issue.
