### ISSUE TITLE
move openeo specific process listing to dedicated page

### ISSUE THREAD

**Issue by soxofaan** [eu-cdse/documentation#184]
like  #183  but for processes

https://github.com/eu-cdse/documentation/blob/c146875602cee495bcd837edaf934992856ea230/APIs/openEO/openEO.qmd#L74-L79

**Comment by soxofaan** [comment]
update this too:
https://github.com/eu-cdse/documentation/blob/0d92a8699687f2087ae08388de9cc4a0fd0b58bd/APIs/openEO/Python_Client/Python.qmd#L108-L112

**Comment by Pratichhya** [comment]
#205
