### ISSUE TITLE
API page lists everything under 'catalog api'

### ISSUE THREAD

**Issue by jdries** [eu-cdse/documentation#186]
Small issue: the main api page has a table of contents that indicates all these services as catalogs:

![image](https://github.com/eu-cdse/documentation/assets/5937096/d5a089d1-b12e-42cc-8111-617b4eb5a308)

**Comment by Pratichhya** [comment]
I will immediately remove that heading to avoid confusion.

**Comment by Pratichhya** [comment]
@jdries @JanssenBrm Also, I was thinking (later) how about adding short introduction to main API and Data page for each of these sub headings?

**Comment by jdries** [comment]
yes, makes a lot of sense because these names don't tell much for a novice user

The main webpage even has some introductory text to copy from:
https://dataspace.copernicus.eu/analyse/apis
