### ISSUE TITLE
Sentinel-2 Level 1B data: check 'offered data' table

### ISSUE THREAD

**Issue by MartinePaepen** [eu-cdse/documentation#188]
https://documentation.dataspace.copernicus.eu/Data/Sentinel2.html

In the Offered Data table for the Sentinel-2 Level 1B section, there are 2 almost identical rows. Only the Temporal Extent is different and this seems to make no sense. Should there be an other Available date in the first row?

**Comment by Pratichhya** [comment]
@MartinePaepen , thank you for noticing. It is updated with the updated with variation in the temporal extent and the archive status.
