### ISSUE TITLE
Data Copernicus Operations Dashboard: 'contact link' is not working

### ISSUE THREAD

**Issue by MartinePaepen** [eu-cdse/documentation#189]
https://documentation.dataspace.copernicus.eu/Data/Dashboard.html

on the bottom of the page, the 'contact us' link is not working.

I see that the 'contact us' link is not working on other pages neither, eg:
- https://documentation.dataspace.copernicus.eu/Support.html
- https://documentation.dataspace.copernicus.eu/Registration.html

I logged myself in in the general portal and this makes no difference.

**Comment by soxofaan** [comment]
on https://documentation.dataspace.copernicus.eu/Data/Dashboard.html it is just a `mailto:info_obs.dasboard@omcs.atlassian.net`  link and if I click it (Firefox on ubuntu linux), it opens a mail client to send a mail (thunderbird in my case). 
Regardless of clicking the link: that email address looks a bit weird (atlassian.net domain), shouldn't we put a dataspace.copernicus.eu based email there?


On https://documentation.dataspace.copernicus.eu/Support.html and https://documentation.dataspace.copernicus.eu/Registration.html  there indeed seems to be a syntax error in the mailto link

**Comment by soxofaan** [comment]
I already fixed the mailto syntax errors in 014624c6591b0e57e86d057794d44593c5fef65e

But there is some more room for improvements I think:

```
Registration.md
35:If you have an issue with registering or you want to deregister, please 
[contact us](mailto:help-login@dataspace.copernicus.eu?Subject=Subject%20Text&Body=Your%20comments) directly.

FAQ.qmd
191:    Please e-mail the 
<a href="mailto:help-login@dataspace.copernicus.eu">help-login@dataspace.copernicus.eu</a> address for direct support on this matter.

Support.md
9:If you have an issue with registering or you want to deregister, please 
[contact us](mailto:help-login@dataspace.copernicus.eu?Subject=Subject%20Text&Body=Your%20comments) directly.

Data/Dashboard.qmd
34:For any inquiries on the Copernicus Sentinel Operations Dashboard 
[contact us](mailto:info_obs.dasboard@omcs.atlassian.net).
```

- I don't think it is very useful to append `?Subject=Subject%20Text&Body=Your%20comments` to the mailto links, just to initialize the email subject/body with generic placeholders. I would only add these if there is a useful non-generic subject/body to specify (e.g. something  like `Subject=Registration problem` from registration.html)
- I see `help-login@dataspace.copernicus.eu` used in a couple of places, but why is that "help-login", and what does that mean? Is that specific for login related help? are there other support emails as well?
- FAQ.qmd uses HTML  link `<a href="mailto...`  unlike markdown links in other places

**Comment by Slegersj** [comment]
These are correct email addresses for their purpose:
- "help-login@dataspace.copernicus.eu" is a dedicated support email address for user registration issues and requests to deregister.
- "info_obs.dasboard@omcs.atlassian.net" comes from and corresponds to https://operations.dashboard.copernicus.eu/about.html

**Comment by KanerLev** [comment]
> https://documentation.dataspace.copernicus.eu/Data/Dashboard.html
> 
> on the bottom of the page, the 'contact us' link is not working.
> 
> I see that the 'contact us' link is not working on other pages neither, eg:
> 
> * https://documentation.dataspace.copernicus.eu/Support.html
> * https://documentation.dataspace.copernicus.eu/Registration.html
> 
> I logged myself in in the general portal and this makes no difference.



Your case may be due to the Windows settings for Default apps. If the Email default app on the Windows you use is set to a browser (Chrome, Mozilla, Edge etc.) it may seem that the 'contact us' link is not working. However if you change Email default app to for example Outlook, you'll see that the 'contact us' link works. You can see it in the mailto_gif.gif I attached.

![mailto_gif](https://github.com/eu-cdse/documentation/assets/78963238/6d6e922d-ad87-4404-9704-6e0ed29daa1d)

If this doesn't work, please let us know.
