### ISSUE TITLE
openEO sample notebooks unable to update in publish

### ISSUE THREAD

**Issue by Pratichhya** [eu-cdse/documentation#193]
The rendering of the notebooks was not transferred when migrated to the publish branch. It leads to the NOT FOUND page.

**Comment by Pratichhya** [comment]
Ahh @jdries . Its ok, not tooo late and thank you for your help . Did you already commit or fix it?

**Comment by jdries** [comment]
I committed a fix to the action indeed, and it worked, for instance:
https://documentation.dataspace.copernicus.eu/notebook-samples/openeo/UDF.html
Can you restore the TOC, so they are visible? Most critical problem is that users now see very limited documentation for openEO, good that we didn't make too big announcements yet.

**Comment by Pratichhya** [comment]
> I committed a fix to the action indeed, and it worked, for instance: https://documentation.dataspace.copernicus.eu/notebook-samples/openeo/UDF.html Can you restore the TOC, so they are visible? Most critical problem is that users now see very limited documentation for openEO, good that we didn't make too big announcements yet.

Sure. The table of content is restored.
