### ISSUE TITLE
Images in Jupyter Hub and OpenEO Docuemtation Sections are loading very slow (>10 sec.)

### ISSUE THREAD

**Issue by jurrydelamar** [eu-cdse/documentation#209]
Timestamp: 10/07/23, 11:00

**Comment by soxofaan** [comment]
I noticed slow loading too sometimes.

The docs repo apparently has some images that are pretty large in size (in web perf terms). 
For example the top 20 largest PNG files are all larger than 1MB:
```
$ python -c 'from pathlib import Path; print("\n".join(f"{s:11_d} {p}" for (s,p) in sorted(((p.stat().st_size, str(p)) for p in  Path(".").glob("**/*.png")), reverse=True)[:20]))'
  4_084_447 _site/Applications/_images/webeditor.png
  4_084_447 Applications/_images/webeditor.png
  3_914_985 Applications/_images/Browser_Spectral_Explorer.png
  2_708_498 Applications/_images/PlazaLanding.png
  2_431_824 _site/_images/registration/Welcome.png
  2_431_824 _images/registration/Welcome.png
  2_331_274 _site/_images/registration/Verify.png
  2_331_274 _images/registration/Verify.png
  1_952_128 _site/Applications/_images/FirstLook_jupyter.png
  1_853_010 _site/Applications/_images/jobs.png
  1_853_010 Applications/_images/jobs.png
  1_737_156 _site/Applications/_images/Service_report.png
  1_737_156 Applications/_images/Service_report.png
  1_605_653 _site/Applications/_images/jupyter_login.png
  1_605_653 Applications/_images/jupyter_login.png
  1_582_616 _site/Applications/_images/PlazaManageService.png
  1_582_616 Applications/_images/PlazaManageService.png
  1_531_575 _site/Applications/_images/Reporting.png
  1_531_575 Applications/_images/Reporting.png
  1_411_515 _site/Applications/_images/billing.png
```

**Comment by soxofaan** [comment]
WebP will help, but is maybe more tedious to work with during authoring/maintenance.

Even while sticking to PNG, there is room for improvement. E.g. I tried https://tinypng.com/ on  Applications/_images/webeditor.png and it went from 4.1MB to 1.0MB

related to my remark about the 5000px size, e.g. `Applications/_images/webeditor.png` looks unnecessarily upscaled :
![Screenshot from 2023-07-17 15-53-55](https://github.com/eu-cdse/documentation/assets/44946/80323996-f4f8-4b57-979f-3da262ae1648)
note that these blurry edges contribute to bad PNG compression ratios as well

**Comment by Pratichhya** [comment]
@soxofaan, Thank you for the suggestion of  https://tinypng.com/ , it was helpful.
Thus updated almost all the images with size>1MB.

- [x]  4_084_447 _site/Applications/_images/webeditor.png
- [ ]  3_914_985 Applications/_images/Browser_Spectral_Explorer.png (couldn’t find the image)
- [x]  2_708_498 Applications/_images/PlazaLanding.png
- [x]  2_431_824 _site/_images/registration/Welcome.png
- [x]  2_331_274 _images/registration/Verify.png
- [x]  1_952_128 _site/Applications/_images/FirstLook_jupyter.png
- [x]  1_853_010 _site/Applications/_images/jobs.png
- [x]  1_737_156 _site/Applications/_images/Service_report.png
- [x]  1_605_653 _site/Applications/_images/jupyter_login.png
- [x]  1_582_616 _site/Applications/_images/PlazaManageService.png
- [x]  1_531_575 _site/Applications/_images/Reporting.png
- [x]  1_411_515 _site/Applications/_images/billing.png

**Comment by soxofaan** [comment]
FYI: at my previous job we integrated image optimization in the build phase of a website, using CLI tools like https://pngquant.org/ if I remember correctly.
Doing it manually with  https://tinypng.com/ now is a good quick fix, but doing it automatically (e.g. as pre-commit hook, or in build phase) is more future proof of course. Alternatively, I guess there are CDN-level solutions that provide these kind of image optimization features as well.

**Comment by Pratichhya** [comment]
@soxofaan Thank you for the idea. I also thought doing the same every time for all the images may not be a good solution. But I had no idea that such a solution was possible. In that case, maybe I can create a new issue to look into it and link to this issue for reference. Thank you again.

**Comment by jurrydelamar** [comment]
I know there is a wordpress-plugin to automatically do the conversions to webP.
Probably there is also one for tinyPNG.
Then following each image upload you simply run the plugin…

Von: Pratichhya ***@***.***>
Gesendet: Donnerstag, 20. Juli 2023 13:19
An: eu-cdse/documentation ***@***.***>
Cc: de la Mar, Jurry ***@***.***>; Author ***@***.***>
Betreff: Re: [eu-cdse/documentation] Images in Jupyter Hub and OpenEO Docuemtation Sections are loading very slow (>10 sec.) (Issue #209)


@soxofaan<https://github.com/soxofaan> Thank you for the idea. I also thought doing the same every time for all the images may not be a good solution. But I had no idea that such a solution was possible. In that case, maybe I can create a new issue to look into it and link to this issue for reference. Thank you again.

**Comment by Pratichhya** [comment]
Hi @jurrydelamar,

If there is already a plugin or package for such a task, then it shouldn't be an issue to include them in action/pre-commit hook as Stefaan suggested.

**Comment by soxofaan** [comment]
we're not using wordpress here, so such a plugin might not be that easy to adapt in our workflows.

I found https://github.com/gdubicki/pre-commit-pngquant however, but it assumes the `pngquant` tool is available on your system, so that might be a bit annoying to get working
