### ISSUE TITLE
Could not download products using OData API (401 Unauthorized)

### ISSUE THREAD

**Issue by fangzhegeo** [eu-cdse/documentation#221]
Today , I found I could not download products using OData API, despite the request header `"Authorization: Bearer {KEYCLOAK_TOKEN}"` has been added. The response is 401 Unauthorized error.  Upon inspecting the network using Chrome's F12, I noticed the some additional headers starting with a colon, such as `":Authority: zipper.dataspace.copernicus.eu."` 

I have confirmed that my access token is valid and has the necessary permissions, and my code was functioning correctly in the past. So I guess the issue is related to these new headers, which rely on the new feature in HTTP/2. However, since my client does not support HTTP/2, I am unable to perform further testing.

I would like to know if the introduction of the new headers (e.g., ":Authority") results in the 401 Unauthorized error. If so, is there any workaround available to download products by bypassing the use of HTTP/2?

**Comment by Pratichhya** [comment]
Hi @fangzhegeo,

I recommend you submit this issue as a ticket ([here](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new)) for the quick response and proper flow among the concerned group.

**Comment by fangzhegeo** [comment]
> 

Thanks for your suggestion @Pratichhya . I have submited it to the Help Center.
