### ISSUE TITLE
APIs/OData/Product Download/Python Documentation Update Proposal

### ISSUE THREAD

**Issue by KanerLev** [eu-cdse/documentation#228]
Dear,

When trying this Python code in APIs/OData/Product Download of the Copernicus Data Space Ecosystem Documentation [here](https://documentation.dataspace.copernicus.eu/APIs/OData.html#:~:text=O%20example_odata.zip-,Python,-import%20requests%0Asession), running the exact code gives the following error: {"detail":"Wrong token format?"}

However changing the header update line 
from session.headers.update({'Authorization': 'Bearer KEYCLOAK_TOKEN'}) 
to session.headers.update({'Authorization': f'Bearer {keycloak_token}'}), gives no error and results in successfully downloaded product.zip.

Please see attached screencasts for both cases.
Is there a need to change this header update line accordingly?
![Odata_documentation_as_is](https://github.com/eu-cdse/documentation/assets/78963238/4f25a973-524f-485f-bf72-d42350683898)

![Odata_documentation_proposed](https://github.com/eu-cdse/documentation/assets/78963238/acfe8d2c-75ac-4244-a2c1-6bd581e7800e)

Thank you and kind regards

**Comment by KanerLev** [comment]
@abuiquoc

**Comment by abuiquoc** [comment]
Included in https://github.com/eu-cdse/documentation/pull/229
