### ISSUE TITLE
Register documentation error

### ISSUE THREAD

**Issue by zivankaraman** [eu-cdse/documentation#234]
I think there's an error in the documentation on the page https://documentation.dataspace.copernicus.eu/Registration.html.
It says 'You will now get the Copernicus Data Space Ecosystems login form. Click “here” in the bottom.'
I think it should say 'You will now get the Copernicus Data Space Ecosystems login form. Click “**REGISTER**” **on the right**.'

**Comment by soxofaan** [comment]
good catch.

And why not link directly to the registration form? Docs now spend two paragraphs and two (large) screenshots to just get to the registration page

**Comment by Pratichhya** [comment]
@zivankaraman @soxofaan Thank you for pointing out the error and sharing your suggestions. As you suggested, we have updated the page accordingly.
Please feel free to share any further feedback or suggestions you may have throughout the documentation.  Thank you again :).
