### ISSUE TITLE
Nodes feature not documented

### ISSUE THREAD

**Issue by jolyonm** [eu-cdse/documentation#237]
The OData Nodes feature, as demonstrated in the data_basics.ipynb Jupyter notebook is not described in the OData API documentation

# Nodes() method lets us traverse the directory tree and retrieve single file from the product
url = f"{catalogue_odata_url}/Products({product_identifier})/Nodes({product_name})/Nodes(MTD_MSIL1C.xml)/$value"

**Comment by abuiquoc** [comment]
added in:
https://github.com/eu-cdse/documentation/pull/245
