### ISSUE TITLE
Service desk page => improve intro

### ISSUE THREAD

**Issue by jdries** [eu-cdse/documentation#24]
Current intro:

[Service Desk]
In case of any questions that cannot be found in this documentation section, users can ask for support related to questions on the use of the Copernicus Data Space Ecosystem.

This sentence is a bit difficult. I think we try to explain here what type of questions are allowed to be sent to the service desk?
Maybe write a longer paragraph, explaining what our support covers and what not.

**Comment by MartinePaepen** [comment]
We will replace it by
'If the documentation portal does not provide the solution to your questions related to the use of the Copernicus Data Space Ecosystem, this page describes how to ask for support. '
