### ISSUE TITLE
error in 'to get the token' - to many "\"

### ISSUE THREAD

**Issue by bomansb** [eu-cdse/documentation#25]
In the Product Download section under API OData, there are some "\" to much in :

KEYCLOAK\_TOKEN=$(curl -s --location --request POST ''https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token'  \
    --data-urlencode 'grant\_type=password' \
    --data-urlencode 'username=\<USER\>' \
    --data-urlencode 'password=\<PASSWORD\>' \
    --data-urlencode 'client\_id=CLOUDFERRO\_PUBLIC'|jq .access\_token|tr -d '"')

Referencing to https://creodias.eu/eo-data-catalogue-api-manual where it mentions : 

KEYCLOAK_TOKEN=$(curl -s --location --request POST 'https://identity.cloudferro.com/auth/realms/<BRAND>/protocol/openid-connect/token' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=<USER>' \
--data-urlencode 'password=<PASSWORD>' \
--data-urlencode 'client_id=CLOUDFERRO_PUBLIC'|jq .access_token|tr -d '"')

it seems that sometime an "_" was copied as "\_".

Please correct.  Thanks.

**Comment by fwfichtner** [comment]
There are also more typos when the variable is used, but even after fixing this I cannot make it work.

@bomansb does it work for you?

**Comment by bomansb** [comment]
Hey Florian, 
thanks for your information, 
can you be more specific on the typo's, 
we will look at it asap, 
Best regards, 
Bart Bomans

**Comment by fwfichtner** [comment]
There is a "C" missing in https://github.com/eu-cdse/documentation/blame/main/APIs/OData.md#L235. I saw that you changed the `client_id`, now it works for me. Thank you!

**Comment by Pratichhya** [comment]
Thank you. Corrected
