### ISSUE TITLE
Bugs in example notebooks

### ISSUE THREAD

**Issue by clausmichele** [eu-cdse/documentation#251]
So, I've started from here and launched JupyterLab: https://dataspace.copernicus.eu/analyse/jupyter-notebooks

Some feedbacks:
- The openeo package is not up to date, version 0.20 instead of the latest 0.22
- The notebooks Load_Collection.ipynb UDP.ipynb and UDF.ipynb return an error when doing the download, since the output folder does not exist:
```python
- ---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 1
----> 1 rescaled_cube.download("output/rescale_s2.tiff")

File /opt/conda/envs/openeo/lib/python3.11/site-packages/openeo/rest/datacube.py:1918, in DataCube.download(self, outputfile, format, options)
   1916     format = guess_format(outputfile)
   1917 cube = self._ensure_save_result(format=format, options=options)
-> 1918 return self._connection.download(cube.flat_graph(), outputfile)

File /opt/conda/envs/openeo/lib/python3.11/site-packages/openeo/rest/connection.py:1478, in Connection.download(self, graph, outputfile, timeout)
   1469 response = self.post(
   1470     path="/result",
   1471     json=request,
   (...)
   1474     timeout=timeout or DEFAULT_TIMEOUT_SYNCHRONOUS_EXECUTE,
   1475 )
   1477 if outputfile is not None:
-> 1478     with Path(outputfile).open(mode="wb") as f:
   1479         for chunk in response.iter_content(chunk_size=None):
   1480             f.write(chunk)

File /opt/conda/envs/openeo/lib/python3.11/pathlib.py:1044, in Path.open(self, mode, buffering, encoding, errors, newline)
   1042 if "b" not in mode:
   1043     encoding = io.text_encoding(encoding)
-> 1044 return io.open(self, mode, buffering, encoding, errors, newline)

FileNotFoundError: [Errno 2] No such file or directory: 'output/rescale_s2.tiff'
```
- Running firstly the notebook Batch_job.ipynb would create the output folder, but it's not obvious every one would do that.

**Comment by Pratichhya** [comment]
@clausmichele The reported issue regarding the output folder is solved in the notebooks. It will soon reflect in JupyterLab, too, since the content is mirrored for documentation; it will reflect there, too, when the sub-module is updated.

Regarding the version update. We have not yet adopted the automatic version update. Thus, for the time being, users might have to update the available packages based on their requirements. @dirkdaems, isn't that the case?
