### ISSUE TITLE
OpenSearch Polygon search

### ISSUE THREAD

**Issue by agrouaze** [eu-cdse/documentation#253]
An example of successful query using APIHub : https://apihub.copernicus.eu/apihub/search 
```python
beginPosition:[2023-08-15T23:35:00.000000Z TO 2023-08-16T00:25:00.000000Z] AND filename:S1?_IW_SLC* AND (footprint:"Intersects(POLYGON ((-67.7 52.4, -67.5 -52.3, -90.0 -54.0, -93.9 -50.6, -94.0 50.4, -67.7 52.4)))" )
```
Since this service will be deprecated soon I want to use : 'http://catalogue.dataspace.copernicus.eu/resto/api/collections/search.json?' 
Unfortunately I cannot find equivalent example in https://documentation.dataspace.copernicus.eu/APIs/OpenSearch.html 
There is the `box` keyword but it is not polygon...
Could you help us on this topic?

**Comment by Pratichhya** [comment]
@agrouaze implementation for the requested changes in documentation may take some time. In the meanwhile, you can also, [submit a request](https://helpcenter.dataspace.copernicus.eu/hc/en-gb) in this regard which could be a quicker option.

**Comment by abuiquoc** [comment]
Here is an example with the POLYGON search:
```
https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$filter=OData.CSC.Intersects(area=geography%27SRID=4326;POLYGON((-8.478158930821758%2037.819546000392904,-8.466942135721926%2037.819546000392904,-8.466942135721926%2037.83846844781075,-8.478158930821758%2037.83846844781075,-8.478158930821758%2037.819546000392904))%27)%20and%20ContentDate/Start%20gt%202020-02-27T00:00:00.000Z%20and%20ContentDate/Start%20lt%202020-03-13T00:00:00.000Z&$orderby=ContentDate/Start
```
