### ISSUE TITLE
Create documentation for VITO mosaics

### ISSUE THREAD

**Issue by JanssenBrm** [eu-cdse/documentation#256]
As the VITO worldcover mosaics are added to the ecosystem, it is important to also include the information in the documentation:

- [ ] Provide a general description of the data sets
- [ ] Provide a guide to the WorldCover website for more information
- [ ] Add a link to the catalogue

**Comment by Pratichhya** [comment]
@JanssenBrm I assume it is completed and related to [this ](https://documentation.dataspace.copernicus.eu/Data/Additional.html#sentinel-2-mosaics)? In that case, can I close the ticket?

**Comment by JanssenBrm** [comment]
Correct, if the content is working and correct, the ticket can be closed.
