### ISSUE TITLE
Explanation of harmonize values missing

### ISSUE THREAD

**Issue by StanHatko** [eu-cdse/documentation#269]
The process API example to download the raw bands data https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Process/Examples/S2L2A.html#all-s2l2a-raw-bands-original-data-no-harmonization says to "Learn about harmonization [here](https://documentation.dataspace.copernicus.eu/Data/Sentinel2.html#harmonize-values)."

I click on that link and cannot find a single mention of harmonizing values or harmonization anywhere on that page. Could you please either add an explanation of harmonization to that page or fix the link if there is another page explaining harmonization?

**Comment by Pratichhya** [comment]
@StanHatko thank you for notifying us. 

@gobaRules Anja, @versniksinergise  could you please help us in following up with this issue? Does any additional information regarding harmonization need to be included in the data section? Or a separate page is required?

**Comment by gmajcen-planet** [comment]
fixed here: https://github.com/eu-cdse/documentation/pull/300
