### ISSUE TITLE
Documentation/APIs/OData/Query By Attributes

### ISSUE THREAD

**Issue by KanerLev** [eu-cdse/documentation#273]
On Documentation/APIs/OData/Query By Attributes (https://documentation.dataspace.copernicus.eu/APIs/OData.html#:~:text=Attachment%201%20%2D%20Coming%20soon), it reads "(Attachment 1 - Coming soon)". 

Is it possible to facilitate the provision of the attachment? Or provide equivalent information?
![attributes_attachment](https://github.com/eu-cdse/documentation/assets/78963238/89b9fdd4-e04e-4789-a719-d0b489b98267)

**Comment by abuiquoc** [comment]
We are aware of this lack. The issue has been forwarded to the Catalogue team.

**Comment by abuiquoc** [comment]
@Slegersj This attachment does not apply to attributes.

**Comment by Slegersj** [comment]
Any news from the Catalogue team about updating this section in the documentation?

**Comment by Slegersj** [comment]
#550 merged
