### ISSUE TITLE
Documentation/APIs/Sentinel Hub/Statistical API/Examples for Statistical API - download link

### ISSUE THREAD

**Issue by KanerLev** [eu-cdse/documentation#276]
On Sentinel Hub Documentation [here](https://docs.sentinel-hub.com/api/latest/api/statistical/examples/#:~:text=with%20all%20examples-,can%20be%20downloaded,-here.): 

the download link ( https://docs.sentinel-hub.com/api/latest/ba8a238c13144db9ad60bbffef26c241/statistical_api_sh_docs.ipynb ) seems not to be stable over long term. Is it possible for you to change the link to a stable long term link **on** https://docs.sentinel-hub.com/api/latest/api/statistical/examples ?

Once (if) you do that, I'll update the CDSE documentation accordingly.

![statistical API examples download link](https://github.com/eu-cdse/documentation/assets/78963238/db441cef-f669-4fb9-a0f0-d7fa8fb42f92)

**Comment by gmajcen-planet** [comment]
fixed here: https://github.com/eu-cdse/documentation/pull/300

**Comment by gmajcen-planet** [comment]
fixed/removed here: https://github.com/eu-cdse/documentation/pull/300
