### ISSUE TITLE
Documentation/Analyze Data/APIs & Documentation/Analyze Data/APIs/Catalog APIs

### ISSUE THREAD

**Issue by KanerLev** [eu-cdse/documentation#277]
1) On Documentation/Analyze Data/APIs, is it appropriate add "S3" to the list?
![Catalogue APIs](https://github.com/eu-cdse/documentation/assets/78963238/661e7049-8c0b-477b-9c6d-72d46e82f321)
So change the text 
From:
The Copernicus Data Space Ecosystem catalogue is a web service that can be queried through 4 different REST protocols, so that you can choose the one that works best for you.

- OData
- STAC
- OpenSearch
- Sentinel Hub catalogue

To:

The Copernicus Data Space Ecosystem catalogue is a web service that can be queried through **5 different REST** protocols, so that you can choose the one that works best for you.

**- S3**
- OData
- STAC
- OpenSearch
- Sentinel Hub catalogue

2) If yes, then is it possible to provide a 1-2 sentence(s) on S3 so we can display it on Documentation/Analyze Data/APIs/Catalog APIs/ Go-to APIs for data downloads from the Ecosystem?
![Catalog APIs](https://github.com/eu-cdse/documentation/assets/78963238/ad65f3fd-7166-43c8-a7f6-a2ae8d872a17)

**Comment by abuiquoc** [comment]
On documentation portal S3 is included as a "additionally API":
https://documentation.dataspace.copernicus.eu/APIs.html#additionally
is not included in Catalogue APIs, so i would leave it like it is.
