### ISSUE TITLE
How to use the "box" ROI parameter in the OpenSearch Copernicus Data Space API

### ISSUE THREAD

**Issue by ggcr** [eu-cdse/documentation#28]
In the documentation it is briefly mentioned the following on the `Geography and time-frame` section on this [page](https://documentation.dataspace.copernicus.eu/#/APIs/OpenSearch).

> box - region of interest, defined as the rectangle with given (west,south,east,north) values

Could we have an example of how to actually use it? I haven't been able to found any. 

Thanks! And awesome work I am very motivated for this project.

**Comment by Slegersj** [comment]
Sample query added in the documentation on the [page](https://documentation.dataspace.copernicus.eu/#/APIs/OpenSearch).
