### ISSUE TITLE
Collection names when querying OData API

### ISSUE THREAD

**Issue by alistaireverett** [eu-cdse/documentation#282]
Under the section on querying collections (https://documentation.dataspace.copernicus.eu/APIs/OData.html#query-collection-of-products), the collections listed as available are:

![image](https://github.com/eu-cdse/documentation/assets/7837535/0ebcc611-88fa-474b-bcd2-9348affb8f1c)

However, when submitting a query for, for example, the collection `Sentinel1`, nothing is returned, while `SENTINEL-1` works fine. So I think the collection names on the left are incorrect in the documentation?

**Comment by Pratichhya** [comment]
@abuiquoc, was it a general name given in the documentation to highlight, or should a specific name, as a suggestion for the request to be included in the documentation?

**Comment by Pratichhya** [comment]
@Slegersj @KanerLev could you please suggest changes if you have handled similar issue encountered? Is it only for Sentinel 1 or other collections too?
