### ISSUE TITLE
Mosaic view in browser https://documentation.dataspace.copernicus.eu/Data/Additional.html#sentinel-2-level-2a-worldcover-annual-cloudless-mosaics-rgbnir

### ISSUE THREAD

**Issue by jolyonm** [eu-cdse/documentation#291]
https://documentation.dataspace.copernicus.eu/Data/Additional.html#sentinel-2-level-2a-worldcover-annual-cloudless-mosaics-rgbnir 

The view in browser page gives and error:

Collection 'byoc-c032fab2-9f5b-444f-a870-47aad66de5c5' has no band 'Red'.

**Comment by Pratichhya** [comment]
@megha-devaraju, could you help us verify what could be the issue, or is the [link ](https://dataspace.copernicus.eu/browser/?zoom=12&lat=46.16733&lng=14.42642&themeId=DEFAULT-THEME&visualizationUrl=https%3A%2F%2Fsh.dataspace.copernicus.eu%2Fogc%2Fwms%2F65330d33-2294-4a71-83a9-7428fdc4157b&evalscript=Ly9WRVJTSU9OPTMKZnVuY3Rpb24gc2V0dXAoKSB7CiAgcmV0dXJuIHsKICAgIGlucHV0OiBbIlJlZCIsIkdyZWVuIiwiQmx1ZSIsICJOSVIiLCAiZGF0YU1hc2siXSwKICAgIG91dHB1dDogeyBiYW5kczogNCB9CiAgfTsKfQpsZXQgZmFjdG9yID0gMS8yMDAwOwpmdW5jdGlvbiBldmFsdWF0ZVBpeGVsKHNhbXBsZSkgewogIHJldHVybiBbZmFjdG9yICogc2FtcGxlLlJlZCxmYWN0b3IgKiBzYW1wbGUuR3JlZW4sZmFjdG9yICogc2FtcGxlLkJsdWUsIHNhbXBsZS5kYXRhTWFzayBdOwp9&datasetId=c032fab2-9f5b-444f-a870-47aad66de5c5&fromTime=2020-01-01T00%3A00%3A00.000Z&toTime=2020-01-01T23%3A59%3A59.999Z&demSource3D=%22MAPZEN%22&cloudCoverage=30#custom-composite)in the documentation incorrect?

**Comment by megha-devaraju** [comment]
Hi @Pratichhya, the link indeed seems outdated. I had initially sent the band names as Red, Green, Blue and NIR but after referring to documentation, I changed the band names in the script as well as collection, but looks like the link refers to the previous script. You could create a new link by viewing the Sentinel-2 Mosaics from Data Collection drop down menu in the Copernicus Browser. 

Share Link: https://sentinelshare.page.link/918j

**Comment by Pratichhya** [comment]
Thank you, @megha-devaraju, for confirming. Thank you, @jolyonm, for a heads-up.

The link is now updated and should be reflected in the documentation shortly.

**Comment by megha-devaraju** [comment]
Looks like this link is broken again. The correct link: link.dataspace.copernicus.eu/vhp

**Comment by KanerLev** [comment]
> Looks like this link is broken again. The correct link: [link.dataspace.copernicus.eu/xvs](link.dataspace.copernicus.eu/xvs)

@megha-devaraju the last provided link opens a 404 page: 
![404](https://github.com/eu-cdse/documentation/assets/78963238/5ffb574b-3d46-4c34-bd40-adfdb67fde26)

Can you provide the functional link for the Open in Browser button in [Sentinel-2 Level 2A WorldCover Annual Cloudless Mosaics (RGBNIR)](https://documentation.dataspace.copernicus.eu/Data/Additional.html#sentinel-2-level-2a-worldcover-annual-cloudless-mosaics-rgbnir) ?

We tried to create one by viewing the Sentinel-2 Mosaics from Data Collection drop down menu in the Copernicus Browser, however didn't succeed:
![no_success](https://github.com/eu-cdse/documentation/assets/78963238/a99031ba-c1fb-4ed9-b3f8-ab9795ded5d9)

**Comment by Pratichhya** [comment]
@KanerLev, as she suggested earlier I assume this is the corrected link you are referring to https://link.dataspace.copernicus.eu/7qk

**Comment by megha-devaraju** [comment]
Hi @KanerLev, I think it was missing the 'https://' before. I have edited the link in my previous comment. Hope that helps.
