### ISSUE TITLE
S3 API documentation bug regarding recursive parameter usage

### ISSUE THREAD

**Issue by janwesterkamp** [eu-cdse/documentation#296]
Hello,

the [S3 API documentation](https://documentation.dataspace.copernicus.eu/APIs/S3.html) recomends the [**-recursive**](https://github.com/eu-cdse/documentation/blob/6a96d3168445ebbbc0390a32bf5c3c30b7898ec5/APIs/S3.md?plain=1#L50) option for fetching directories - but it should be **--recursive** or **-r** instead.

Another issue I noticed is, that the s3cmd (2.3.0 on macOS) does not accept the recursive option to be placed in any order with otheres. Placing it in front of the **get** works fine, i.e.:

`s3cmd --stats -c ~/.s3cfg -r get s3://EODATA/Sentinel-2/MSI/L2A/2023/06/13/S2B_MSIL2A_20230613T102609_N0509_R108_T32UMA_20230613T151004.SAFE/`

Note: I also added the **--stats** option here too.

**Comment by Pratichhya** [comment]
@abuiquoc could you help us to confirm the suggested changes for the documentation?

@janwesterkamp with the issue regarding s3cmd (2.3.0 on macOS) not accepting the recursive option, could you please either post it in a forum or submit a ticket for quicker response and solution to the issue?

**Comment by Slegersj** [comment]
The [S3 API documentation](https://documentation.dataspace.copernicus.eu/APIs/S3.html) has been updated.
