### ISSUE TITLE
CORS error to fetch Sen2 L2 data with Odata URI

### ISSUE THREAD

**Issue by rifatSDAS** [eu-cdse/documentation#299]
For our web-geospatial app we need Sentinel 2 Level 2 data. So far from our client side (for development) we are managed to fetch Quick Look JPEG by give a user define query with OpenSearch URI and plot them on our client side leaflet web map. The call made from localhost:5502. But having CORS issues for downloading product ZIP file. We use FireFox developer edition, v117.0.1. The error is, e.g., 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://catalogue.dataspace.copernicus.eu/odata/v1/Products(57e17761-06dc-4507-9808-8d4d06b4e681)/$value. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 301.

These are the outputs from console for OPTIONS and GET 

**OPTIONS**

_Response Headers_
HTTP/2 301 
date: Mon, 25 Sep 2023 16:52:20 GMT
content-type: text/html
content-length: 162
location: https://zipper.dataspace.copernicus.eu/odata/v1/Products(57e17761-06dc-4507-9808-8d4d06b4e681)/$value
X-Firefox-Spdy: h2

_Request Headers_
OPTIONS /odata/v1/Products(57e17761-06dc-4507-9808-8d4d06b4e681)/$value HTTP/2
Host: catalogue.dataspace.copernicus.eu
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET
Access-Control-Request-Headers: authorization,content-type
Referer: http://127.0.0.1:5502/
Origin: http://127.0.0.1:5502
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
TE: trailers

**GET**

**Request Headers**
GET /odata/v1/Products(57e17761-06dc-4507-9808-8d4d06b4e681)/$value undefined
Host: catalogue.dataspace.copernicus.eu
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer example-21321access_token.1213
Content-Type: application/octet-stream
Origin: http://127.0.0.1:5502
Connection: keep-alive
Referer: http://127.0.0.1:5502/
Cookie: any-example-cookies
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site

And this is the JavaScript code block to fetch product ZIP file with Odata URI,

```
const xhr = new XMLHttpRequest();
xhr.overrideMimeType('application/json');
xhr.onreadystatechange = function () {
      if (this.readyState == 4 && this.status == 200) {
            readJSON(this);
            window.open().document.write(xhr.responseText);
            }
};
xhr.open('GET', `https://catalogue.dataspace.copernicus.eu/odata/v1/Products(${id})/$value`, true); 
xhr.setRequestHeader('Authorization', `Bearer ${accessToken}`);
xhr.setRequestHeader('Content-Type', 'application/octet-stream');
xhr.setRequestHeader('Origin', 'http://127.0.0.1:5502');
xhr.withCredentials = true;
xhr.send();
```

Maybe we are doing in a wrong direction. So, any insight and comments would be appreciated. 
For information, old version of OpenSearch and Odata URI, e.g., https://scihub.copernicus.eu/dhus/odata/v1/Products, were working for product downloading from our client side from same localhost:5502. Lastly, if more information require from us please let us know :-)

Best regards

**Comment by Pratichhya** [comment]
@rifatSDAS thank you for your feedback, @abuiquoc should we pass it to the service desk? Do you have any feedback or comments in this regard?

**Comment by Slegersj** [comment]
The topic is being discussed on the Community Forum of the Copernicus Data Space Ecosystem:
[https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/posts/13838819603485-Fetch-Sentinel-2-Level2-data-with-Odata-URI-from-client-side-development-localhost-](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/posts/13838819603485-Fetch-Sentinel-2-Level2-data-with-Odata-URI-from-client-side-development-localhost-)

We recommend to keep this list of issues for reporting issues  with or improvement to the [Documentation portal](https://documentation.dataspace.copernicus.eu/) of the Copernicus Data Space Ecosystem.

Thank you.
On behalf of the Copernicus Data Space Ecosystem Support Team.
