### ISSUE TITLE
Marketplace page saying coming soon but available

### ISSUE THREAD

**Issue by clausmichele** [eu-cdse/documentation#302]
This page states that the marketplace is not yet available:
https://dataspace.copernicus.eu/ecosystem-services/marketplace

but it is, and there's a link to access it here:
https://dataspace.copernicus.eu/analyse/openeo

which points to:
https://marketplace-portal.dataspace.copernicus.eu/catalogue

**Comment by Pratichhya** [comment]
@Slegersj @KanerLev could you please help us in editing these changes in the website?

@clausmichele thank you for pointing out the issues.

**Comment by Slegersj** [comment]
@clausmichele @Pratichhya
Strange, this old page https://dataspace.copernicus.eu/ecosystem-services/marketplace was replaced by https://dataspace.copernicus.eu/ecosystem/services in a previous release of the web portal https://dataspace.copernicus.eu/
Let me check with our content manager.

**Comment by Slegersj** [comment]
@clausmichele 
Thank you for bringing this to our attention.

https://dataspace.copernicus.eu/ecosystem-services/marketplace is an old page which is no longer accessible via the web portal  https://dataspace.copernicus.eu/
If you have bookmarked this link, you can delete it. The page has been unpublished.

We now link directly to https://marketplace-portal.dataspace.copernicus.eu/catalogue via https://dataspace.copernicus.eu/ecosystem/services
