### ISSUE TITLE
Access restrictions for Sentinel-2 Level 1B

### ISSUE THREAD

**Issue by Slegersj** [eu-cdse/documentation#325]
According to the documentation, the last two weeks of data should be available to everyone. The mention of "(*) Access restrictions may apply" is only for full archive Deferred available data (cf documentation screenshot attached)

![image](https://github.com/eu-cdse/documentation/assets/124564312/76cdfd99-7c7d-4f55-bc9d-fe15122ae3bd)

I received confirmation that those data is also not available for Copernicus General Users, description on the website seems to be not valid.

(Reference user ticket [785](https://vito414.zendesk.com/agent/tickets/785))

**Comment by KanerLev** [comment]
Fixed. It's publicly available here: https://documentation.dataspace.copernicus.eu/Data/Sentinel2.html
