### ISSUE TITLE
Outdated info on APIs-SentinelHub-API Overview-Processing Unit

### ISSUE THREAD

**Issue by KanerLev** [eu-cdse/documentation#334]
In https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Overview/ProcessingUnit.html,

it reads: _⚠ Costs marked with ** are not yet applied. These will come in effect by September 1st 2023._ 

Can this sentence be excluded as the date September 1st 2023 has passed?
![outdated](https://github.com/eu-cdse/documentation/assets/78963238/adb2b544-8f23-41af-a844-9e72920ecd41)

**Comment by KanerLev** [comment]
We reckon it can be changed from: ⚠ Costs marked with ** are not yet applied. These will come in effect by September 1st 2023.
to: ⚠ Costs marked with ** are not yet applied, they will come into effect in the future. 

(Based on: https://docs.sentinel-hub.com/api/latest/api/overview/processing-unit/#:~:text=%E2%9A%A0%20Costs%20marked%20with%20**%20are%20not%20yet%20applied%2C%20they%20will%20come%20into%20effect%20in%20the%20future.)

Can you confirm?

**Comment by versniksinergise** [comment]
The answer is yes. This can be changed as you suggested. I forwarded this issue once you brough it up here. But it seems like it hasn't been yet fixed in our documentation. But should have informed you here about the forward. I apologize it slipped my mind

**Comment by KanerLev** [comment]
Thanks for the confirmation. Sure.
Accordingly, we'll update the documentation and close this issue soon.
