### ISSUE TITLE
Broken/Lost navigation of "openEO algorithm plaza" docs

### ISSUE THREAD

**Issue by soxofaan** [eu-cdse/documentation#345]
starting at https://documentation.dataspace.copernicus.eu/Applications/AlgorithmPlaza.html :

<img src="https://github.com/eu-cdse/documentation/assets/44946/a94e0143-2877-42d4-b6b6-181329f73414" width="400">

note "openEO algorithm plaza" the navigation in left sidebar
(side note: I think "openEO Algorithm Plaza" should be properly capitalized in the navigation bar an page title)

When I click through on one of the "getting started" links, I don't see anymore where I am in the navigation bar on the left.
For example:.
<img src="https://github.com/eu-cdse/documentation/assets/44946/9414fec2-38e3-42d7-8241-32d9207bb8d6" width="400">

And on https://documentation.dataspace.copernicus.eu/Applications/PlazaDetails/ServiceProviderGuide.html  (and most of its sub-pages) there not even any mentioning that this is about openEO Algorithm Plaza:
<img src="https://github.com/eu-cdse/documentation/assets/44946/aab11717-63a5-4fe2-a1f6-ec319a36cfd6" width="400">

**Comment by Pratichhya** [comment]
A hierarchical arrangement of the pages might provide some overview on the location within guideline(a reminder) : TO DO
