### ISSUE TITLE
#HTTP request sent, awaiting response... 429 Too Many Requests

### ISSUE THREAD

**Issue by ludongxing** [eu-cdse/documentation#351]
I use wget to download Sentinel-1 GRD, and it always reports an error after downloading a few percent or ten percent, does anyone know what's going on? Is it a problem that the token only has a 10-minute expiration date?

Error:
--2023-11-07 17:23:59--  (try: 5)  https://zipper.dataspace.copernicus.eu/odata/v1/Products(4b2e7085-6833-493e-bd4a-cc45942db4c6)/$value
Connecting to zipper.dataspace.copernicus.eu (zipper.dataspace.copernicus.eu)|185.48.234.168|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Retrying.

--2023-11-07 17:24:05--  (try: 6)  https://zipper.dataspace.copernicus.eu/odata/v1/Products(4b2e7085-6833-493e-bd4a-cc45942db4c6)/$value
Connecting to zipper.dataspace.copernicus.eu (zipper.dataspace.copernicus.eu)|185.48.234.168|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2023-11-07 17:24:07 ERROR 429: Too Many Requests.

**Comment by Pratichhya** [comment]
Hi @ludongxing, unfortunately in this repository issue, we try to maintain only issues with regard to the documentation.

Therefore, could you please[ contact user support](https://helpcenter.dataspace.copernicus.eu/hc/en-gb), who will be able to address your issues better and provide you with guidance?
