### ISSUE TITLE
access_token

### ISSUE THREAD

**Issue by 18310812054** [eu-cdse/documentation#352]
通过python访问欧空局获取access_token，显示访问令牌创建无效，服务器返回无效的用户凭证数据

**Comment by soxofaan** [comment]
google translate translates this to
> Accessing ESA via python to obtain access_token shows that the access token creation is invalid and the server returns invalid user credential data


This looks like a user support issue. For Copernicus Data Space Ecosystem user support go to https://helpcenter.dataspace.copernicus.eu/
