### ISSUE TITLE
wget The download keeps displaying server error

### ISSUE THREAD

**Issue by GGOO-has** [eu-cdse/documentation#353]
--2023-11-08 13:58:25--  http://catalogue.dataspace.copernicus.eu/odata/v1/Products(4295af78-b646-469b-90df-7fec8bfe8a64)/$value
正在解析主机 catalogue.dataspace.copernicus.eu (catalogue.dataspace.copernicus.eu)... 185.48.232.146
正在连接 catalogue.dataspace.copernicus.eu (catalogue.dataspace.copernicus.eu)|185.48.232.146|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Moved Temporarily
位置：https://catalogue.dataspace.copernicus.eu/odata/v1/Products(4295af78-b646-469b-90df-7fec8bfe8a64)/$value [跟随至新的 URL]
--2023-11-08 13:58:26--  https://catalogue.dataspace.copernicus.eu/odata/v1/Products(4295af78-b646-469b-90df-7fec8bfe8a64)/$value
正在连接 catalogue.dataspace.copernicus.eu (catalogue.dataspace.copernicus.eu)|185.48.232.146|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://zipper.dataspace.copernicus.eu/odata/v1/Products(4295af78-b646-469b-90df-7fec8bfe8a64)/$value [跟随至新的 URL]
--2023-11-08 13:58:27--  https://zipper.dataspace.copernicus.eu/odata/v1/Products(4295af78-b646-469b-90df-7fec8bfe8a64)/$value
正在解析主机 zipper.dataspace.copernicus.eu (zipper.dataspace.copernicus.eu)... 185.48.234.168
正在连接 zipper.dataspace.copernicus.eu (zipper.dataspace.copernicus.eu)|185.48.234.168|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 500 Internal Server Error
2023-11-08 13:58:28 错误 500：Internal Server Error。

--2023-11-08 13:58:28--  http://catalogue.dataspace.copernicus.eu/odata/v1/Products(db0c8ef3-8ec0-5185-a537-812dad3c58f8)/$value
正在连接 catalogue.dataspace.copernicus.eu (catalogue.dataspace.copernicus.eu)|185.48.232.146|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Moved Temporarily
位置：https://catalogue.dataspace.copernicus.eu/odata/v1/Products(db0c8ef3-8ec0-5185-a537-812dad3c58f8)/$value [跟随至新的 URL]
--2023-11-08 13:58:29--  https://catalogue.dataspace.copernicus.eu/odata/v1/Products(db0c8ef3-8ec0-5185-a537-812dad3c58f8)/$value
正在连接 catalogue.dataspace.copernicus.eu (catalogue.dataspace.copernicus.eu)|185.48.232.146|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://zipper.dataspace.copernicus.eu/odata/v1/Products(db0c8ef3-8ec0-5185-a537-812dad3c58f8)/$value [跟随至新的 URL]
--2023-11-08 13:58:30--  https://zipper.dataspace.copernicus.eu/odata/v1/Products(db0c8ef3-8ec0-5185-a537-812dad3c58f8)/$value
正在连接 zipper.dataspace.copernicus.eu (zipper.dataspace.copernicus.eu)|185.48.234.168|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 500 Internal Server Error
2023-11-08 13:58:31 错误 500：Internal Server Error。
 
Please give me some help
thanks

**Comment by Pratichhya** [comment]
Hi @GGOO-has , it seems like you have been going through several errors when trying to fetch the products. However, in this repository issue, we try to maintain issues mostly with regard to the documentation. 

Therefore, could you please[ contact user support](https://helpcenter.dataspace.copernicus.eu/hc/en-gb), who will be able to address your issues better and provide you with guidance?
