### ISSUE TITLE
python requests library receives chunked encoding problem

### ISSUE THREAD

**Issue by GISer-longchaohuo** [eu-cdse/documentation#355]
![image](https://github.com/eu-cdse/documentation/assets/60539729/1a2b52c0-d367-4250-beeb-8661e82018fa)
import requests

url = f"https://zipper.dataspace.copernicus.eu/odata/v1/Products(a5ab498a-7b2f-4043-ae2a-f95f457e7b3b)/$value"

headers = {"Authorization": f"Bearer {access_token}"}

session = requests.Session()
session.headers.update(headers)
response = session.get(url, headers=headers, stream=True)

with open("product.zip", "wb") as file:
    for chunk in response.iter_content(chunk_size=8192):
        if chunk:
            file.write(chunk)

————————————————————————————————————————
I use official sample requests to download (Sentinel-1) data. python requests library receives chunked encoding problem. How to solve this problem?

**Comment by KanerLev** [comment]
Dear,

We reckon with "I use official sample requests", [OData](https://documentation.dataspace.copernicus.eu/APIs/OData.html#product-download) is referred. If this is the case, we tried to replicate your issue in [JupyterHub](https://jupyterhub.dataspace.copernicus.eu/) and everything seemed to work properly. 

See attached image for our findings and if you haven't, give it a try by following the steps in the screenshot.


![OData Download](https://github.com/eu-cdse/documentation/assets/78963238/0ca33924-f68e-415d-8393-802e208c6bee)

If the issue still persists, we recommend we kindly encourage you to post your question to our [Community Forum](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/topics) so it can reach to experts on Python and they can help you out.

**Comment by GISer-longchaohuo** [comment]
Thank you for your reply, but I used JupyterHub to reproduce it and still encountered the problem. I also found relevant users in the community who encountered similar problems.：
https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/posts/14690032642717-Connection-broken-when-download-data


![image](https://github.com/eu-cdse/documentation/assets/60539729/4a352dea-5516-4b70-9cf1-c684535c1cc5)
![image](https://github.com/eu-cdse/documentation/assets/60539729/d38df635-cd1b-4341-9cb9-41dd5784b0f3)

**Comment by GISer-longchaohuo** [comment]
> 亲爱的，
> 
> 我们认为“我使用官方样本请求”，引用了[OData 。](https://documentation.dataspace.copernicus.eu/APIs/OData.html#product-download)如果是这种情况，我们尝试在[JupyterHub](https://jupyterhub.dataspace.copernicus.eu/)中复制您的问题，一切似乎都工作正常。
> 
> 请参阅附图了解我们的发现，如果您还没有，请按照屏幕截图中的步骤尝试一下。
> 
> ![数据下载](https://user-images.githubusercontent.com/78963238/281662172-0ca33924-f68e-415d-8393-802e208c6bee.PNG)
> 
> 如果问题仍然存在，我们鼓励您将问题发布到我们的[社区论坛](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/topics)，以便联系 Python 专家，他们可以帮助您解决问题。


Thank you for your reply, but I used JupyterHub to reproduce it and still encountered the problem. I also found relevant users in the community who encountered similar problems，The preliminary judgment is that the server connection is interrupted.：
https://helpcenter.dataspace.copernicus.eu/hc/en-gb/community/posts/14690032642717-Connection-broken-when-download-data
