### ISSUE TITLE
Refresh tokens

### ISSUE THREAD

**Issue by msalpiq95** [eu-cdse/documentation#356]
I have been using the access token to download. I understand that it only lasts for 10 minutes and the refresh token for 60 minutes. It is explained in the documentation. 
In my script i try to use the refresh token after the 10 minutes but it still crashes: the refresh token apparently does not work. 
If i use the refresh token to get a new access token, it also does not work. 
I am using Python. 
I am fetching more than 30 products to be able to try the tokens but it always crashes after 600 seconds (10minutes)
I check the keycloak and check that my new token activates but still it does not work. 

Does someone has a solution? Is there missing documentation? As i library i am using creodias, accessing is apparently. keycloak also. 
I believe it is a problem with the tokens, not the code.

**Comment by soxofaan** [comment]
Hi @msalpiq95 

It's recommended to go to https://helpcenter.dataspace.copernicus.eu/ for  Copernicus Data Space Ecosystem user support.

This repository (https://github.com/eu-cdse/documentation) and its issue tracker are purely for development and maintenance of the documentation.
