### ISSUE TITLE
ODATA API Download question

### ISSUE THREAD

**Issue by zhhaxx** [eu-cdse/documentation#364]
I wrote a program in python to query and download Sentinel-3 products, but the downloaded compressed package is only 1kb?

**Comment by KanerLev** [comment]
Hi @zhhaxx ,

Here we aim to maintain issues that are only related to the [documentation portal](https://documentation.dataspace.copernicus.eu/Home.html).

For the issues that require user support, please [contact user support](https://helpcenter.dataspace.copernicus.eu/hc/en-gb).
