### ISSUE TITLE
Is it possible filter with a polygon instead of bbox and item properties (fe: cloudCover,  origin, productType) when querying via the STAC API? 

### ISSUE THREAD

**Issue by pedro-cf** [eu-cdse/documentation#365]
Is it possible filter with a polygon instead of bbox and item properties (fe: cloudCover,  origin, productType) when querying via the STAC API?

**Comment by soxofaan** [comment]
Hi @pedro-cf 

It's recommended to go to https://helpcenter.dataspace.copernicus.eu/ for Copernicus Data Space Ecosystem user support.

This repository (https://github.com/eu-cdse/documentation) and its issue tracker are purely for development and maintenance of the documentation.
