### ISSUE TITLE
Revise the Python script for Access Token

### ISSUE THREAD

**Issue by KanerLev** [eu-cdse/documentation#381]
In https://documentation.dataspace.copernicus.eu/APIs/Token.html#by-python-script, rewrite the script so it is more secure, e.g. by changing the "grant_type": "password".

Helpful code:

```
def refresh_access_token(refresh_token: str) -> str:
    data = {
        "client_id": "cdse-public",
        "refresh_token": refresh_token,
        "grant_type": "refresh_token",
    }
```

    try:
        r = requests.post(
            "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token",
            data=data,
        )
        r.raise_for_status()
    except Exception as e:
        raise Exception(
            f"Access token refresh failed. Reponse from the server was: {r.json()}"
        )

    return r.json()["access_token"]
    #return r.json()

**Comment by Slegersj** [comment]
Closing since the python snippet was removed from the documentation on CF's request (#410).
