### ISSUE TITLE
Rasterio.open jp2 to jpeg error

### ISSUE THREAD

**Issue by Caelin1234** [eu-cdse/documentation#387]
From the Source code: https://documentation.dataspace.copernicus.eu/notebook-samples/geo/odata_basics.html
Section 12. Generate true color RGB I am having trouble with the following code, specifically rasterio.open:

band2 = rasterio.open(f"{Path.home()}/patch_band_2.jp2", driver="JP2OpenJPEG")  # blue
band3 = rasterio.open(f"{Path.home()}/patch_band_3.jp2", driver="JP2OpenJPEG")  # green
band4 = rasterio.open(f"{Path.home()}/patch_band_4.jp2", driver="JP2OpenJPEG") # red

I have tried anaconda, pyvips, but I cannot get the last few steps.

The error is replying that the file format is not supported. Here is the response without my personal paths.  "rasterio._err.CPLE_OpenFailedError: './path/to/image.jp2' not recognized as a supported file format."

Are there any work arounds I'd like to do a big bulk download, but I need to see the code works first. 
Thanks in advance!

**Comment by Caelin1234** [comment]
<img width="584" alt="python rasterio error_with_filename" src="https://github.com/eu-cdse/documentation/assets/41302302/56b086c3-8812-4c1b-9912-826fb8b62bad">
<img width="491" alt="python rasterio errror" src="https://github.com/eu-cdse/documentation/assets/41302302/27fdba1d-e6a1-4901-bbe9-be337c3e853f">

**Comment by Pratichhya** [comment]
@Caelin1234 , thank you for notifying the issue you are facing; we will try to replicate the issue and get back to you as soon as possible.

**Comment by Caelin1234** [comment]
@KanerLev I will share my code since it was extracted from the online hub: https://documentation.dataspace.copernicus.eu/notebook-samples/geo/odata_basics.html

I have commented out all but where the issue is when I run it locally. 
Hopefully this helps my python is not very good. 
Thanks in advance,

###################################################################################################################################
Script generated December 08 2023  
Note python script should be in 3.11 folder if there are 2 versions of python installed)

Prior to the script go into command line and run the following code
https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

pip install requests

pip

"C:\Users\MURRAYCAE\AppData\Roaming\Python\Python311\Scripts" install numpy -U

#pip install rasterio

import matplotlib.pyplot as plt

#Then I added this to solve and discover my pip install remotes wasn't in correct directory or that I was using the wrong python version
#https://sebhastian.com/no-module-named-requests/#google_vignette
#https://stackoverflow.com/questions/47632891/pip-install-returning-invalid-syntax

#import requests
#r = requests.get('https://example.com/api')

#print(r.status_code)

# Then run the collowing code

#####################################################################################################################################
#
# Code was written and extracted from #https://documentation.dataspace.copernicus.eu/notebook-samples/geo/odata_basics.html
#
#####################################################################################################################################

#Packages needed but not in script online:
import numpy as np # Already installed this above in command line
import pandas as pd
import rasterio  # This is part of numpy/pipi

#####################################################################################################################################
# 1. Import python modules
#####################################################################################################################################
# HTTP requests
import requests


# JSON parser
import json

# XML parser
import xml.etree.ElementTree as ET

# system modules
import os
import re
import sys
import random

# data manipulation
import pandas as pd
import numpy as np

# image manipulation
import rasterio
import matplotlib.pyplot as plt
import matplotlib.image
from rasterio.windows import Window

# file manipulation
from pathlib import Path

#####################################################################################################################################
# 2.Query catalogue and get list of products matching the search param
#####################################################################################################################################

# base URL of the product catalogue
catalogue_odata_url = "https://catalogue.dataspace.copernicus.eu/odata/v1"

# search parameters
collection_name = "SENTINEL-2"
product_type = "S2MSI1C"
max_cloud_cover = 1
aoi = "POLYGON((20.888443 52.169721,21.124649 52.169721,21.124649 52.271099,20.888443 52.271099,20.888443 52.169721))"
search_period_start = "2023-06-01T00:00:00.000Z"
search_period_end = "2023-06-10T00:00:00.000Z"

#####################################################################################################################################
# 3. Build and check query
#####################################################################################################################################

search_query = f"{catalogue_odata_url}/Products?$filter=Collection/Name eq '{collection_name}' and Attributes/OData.CSC.StringAttribute/any(att:att/Name eq 'productType' and att/OData.CSC.StringAttribute/Value eq '{product_type}') and OData.CSC.Intersects(area=geography'SRID=4326;{aoi}') and ContentDate/Start gt {search_period_start} and ContentDate/Start lt {search_period_end}"

print(f"""\n{search_query.replace(' ', "%20")}\n""")

#####################################################################################################################################
# 4. Run the query response
#####################################################################################################################################

response = requests.get(search_query).json()
result = pd.DataFrame.from_dict(response["value"])

# print first 3 results
result.head(3)

#####################################################################################################################################
# 5. Add filtering and cloud coverage and repeat the query
#####################################################################################################################################

search_query = f"{search_query} and Attributes/OData.CSC.DoubleAttribute/any(att:att/Name eq 'cloudCover' and att/OData.CSC.DoubleAttribute/Value le {max_cloud_cover})"
print(f"""\n{search_query.replace(' ', "%20")}\n""")

response = requests.get(search_query).json()
result = pd.DataFrame.from_dict(response["value"])

# Print the first 3 results
result.head(3)

#####################################################################################################################################
# 6. Authenticate your account to download files:
#####################################################################################################################################

# Provide CDSE account credentials - replace with your own data
##import os
##
##username = os.environ["my_email"]
##password = os.environ["my_passsword"]
##
### Get authentication token
##import certifi
##
##auth_server_url = "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token"
##data = {
##    "client_id": "cdse-public",
##    "grant_type": "password",
##    "username": username,
##    "password": password,
##}
##
##response = requests.post(auth_server_url, data=data, verify=True, allow_redirects=False)
##access_token = json.loads(response.text)["access_token"]


#Try to modify using this code from: https://documentation.dataspace.copernicus.eu/APIs/Token.html
import json
import requests
def get_access_token(username: str, password: str) -> str:
    data = {
        "client_id": "cdse-public",
        "username": username,
        "password": password,
        "grant_type": "password",
        }
    try:
        r = requests.post("https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token",
        data=data,
        )
        r.raise_for_status()
    except Exception as e:
        raise Exception(
            f"Access token creation failed. Reponse from the server was: {r.json()}"
            )
    return r.json()["access_token"]
        

access_token = get_access_token("caelin.murray@dfo-mpo.gc.ca", "Sophiethecat2015!")

#print('access token =',access_token)                                   # added this to see where code was at

#####################################################################################################################################
# 7. Select product and establish authenticated session
#####################################################################################################################################

# Select identifier of the first product
product_identifier = result.iloc[0, 1]
product_name = result.iloc[0, 2]

#print('product_name=',product_name)                                    # added this to see where code was at

# Establish session
session = requests.Session()
session.headers["Authorization"] = f"Bearer {access_token}"

#print('session')                                                       # added this to see where code was at

os.getcwd ()                                                            # added this to see where code was at
import os                                                               # added this to see where code was at
cwd = os.getcwd ()                                                      # added this to see where code was at

print ('Current Working Directory is: ', cwd) # added this to see where code was at

#os.chdir("C:\\Users\\MURRAYCAE\\Documents\\Sentinel_Data\\Python_outputs") # Data still saving out here C:\Users\MURRAYCAE

ph= Path.home()

#print ("Outputs saved to C:\Users\MURRAYCAE",ph)
 
#####################################################################################################################################
# 8. Get manifestfile
#####################################################################################################################################

# Nodes() method lets us traverse the directory tree and retrieve single file from the product
url = f"{catalogue_odata_url}/Products({product_identifier})/Nodes({product_name})/Nodes(MTD_MSIL1C.xml)/$value"
response = session.get(url, allow_redirects=False)
while response.status_code in (301, 302, 303, 307):
    url = response.headers["Location"]
    response = session.get(url, allow_redirects=False)

file = session.get(url, verify=False, allow_redirects=True)

# Save the product in home directory
outfile = Path.home() / "MTD_MSIL1C.xml"   # I have these already see if I can skip to trpuble shoot
#outfile.write_bytes(file.content)

print ("Manifset file download complete")

#####################################################################################################################################
#
##Added a execution timer.
#Source code: https://datatofish.com/measure-time-to-run-python-script/#:~:text=You%20may%20use%20the%20time%20module%20in%20order,%28%27Execution%20time%20in%20seconds%3A%20%27%20%2B%20str%20%28executionTime%29%29import pandas as pd
#
#####################################################################################################################################

import numpy as np
import time

startTime = time.time()

df = pd.DataFrame(np.random.randint(1,9999,size=(10000000, 1)), columns=['Random numbers'])
df['Random numbers'] = df['Random numbers'].astype(str)

executionTime = (time.time() - startTime)
print('Execution time in seconds: ' + str(executionTime))

#####################################################################################################################################
# 9. Parse manifest file and get bands:
#####################################################################################################################################

# Pass the path of the xml document
tree = ET.parse(str(outfile))
# get the parent tag
root = tree.getroot()

# Get the location of individual bands in Sentinel-2 granule
#Note will have to convert this in a for loop later
band_location = []
band_location.append(f"{product_name}/{root[0][0][12][0][0][1].text}.jp2".split("/"))
band_location.append(f"{product_name}/{root[0][0][12][0][0][2].text}.jp2".split("/"))
band_location.append(f"{product_name}/{root[0][0][12][0][0][3].text}.jp2".split("/"))

#####################################################################################################################################
# 10. Download bands:
#####################################################################################################################################

# Build the url for each file using Nodes() method
bands = []
for band_file in band_location:
    url = f"{catalogue_odata_url}/Products({product_identifier})/Nodes({product_name})/Nodes({band_file[1]})/Nodes({band_file[2]})/Nodes({band_file[3]})/Nodes({band_file[4]})/$value"
    response = session.get(url, allow_redirects=False)
    while response.status_code in (301, 302, 303, 307):
        url = response.headers["Location"]
        response = session.get(url, allow_redirects=False)
    file = session.get(url, verify=False, allow_redirects=True)
    # Save the product in home directory
    outfile = Path.home() / band_file[4]
    #outfile.write_bytes(file.content)
    #bands.append(str(outfile))
    print("Saved:", band_file[4])
    
#####################################################################################################################################
# 11. Prepare cropped batch
#####################################################################################################################################

#%matplotlib inline

# Crop the images to random 1000x1000 patch
xsize, ysize = 1000, 1000
xoff, yoff, xmax, ymax = 0, 0, 0, 0
n = 2

for band_file in bands:
    full_band = rasterio.open(band_file, driver="JP2OpenJPEG") #rasterio issue using rasterio to open images, it also won't open with pyvips
    if xmax == 0:
        xmin, xmax = 0, full_band.width - xsize
    if ymax == 0:
        ymin, ymax = 0, full_band.height - ysize
    if xoff == 0:
        xoff, yoff = random.randint(xmin, xmax), random.randint(ymin, ymax)
    window = Window(xoff, yoff, xsize, ysize)
    transform = full_band.window_transform(window)
    profile = full_band.profile
    crs = full_band.crs
    profile.update({"height": xsize, "width": ysize, "transform": transform})
    with rasterio.open( #rasterio issue using rasterio to open images, it also won't open with pyvips
        f"{Path.home()}/patch_band_{n}.jp2", "w", **profile
    ) as patch_band:
        # Read the data from the window and write it to the output raster
        patch_band.write(full_band.read(window=window))
    print(f"Patch for band {n} created")
    n += 1
    
#####################################################################################################################################
# 12. Generate true color RGB image by reading the patch files
#####################################################################################################################################
#Code block is here, can't convert jp2 to jpg

import pyvips

band2 = pyvips.Image.new_from_file(f"{Path.home()}/patch_band_2.jp2"), image.write_to_file("patch_band_2.jpg") # blue
#band3 = pyvips.Image.new_from_file(f"{Path.home()}/patch_band_3.jp2"), image.write_to_file("patch_band_3.jpg") # green
#band4 = pyvips.Image.new_from_file(f"{Path.home()}/patch_band_4.jp2"), image.write_to_file("patch_band_4.jpg") # red

band2 = rasterio.open(f"{Path.home()}/T34UDD_20230601T094549_B02.jp2", driver="JP2OpenJPEG")  # blue
band3 = rasterio.open(f"{Path.home()}/patch_band_3.jp2", driver="JP2OpenJPEG")  # green
band4 = rasterio.open(f"{Path.home()}/patch_band_4.jp2", driver="JP2OpenJPEG")  # red

red = band4.read(1)
green = band3.read(1)
blue = band2.read(1)

# Normalize the pixel values and apply gain
gain = 2
red_n = np.clip(red * gain / 10000, 0, 1)
green_n = np.clip(green * gain / 10000, 0, 1)
blue_n = np.clip(blue * gain / 10000, 0, 1)

# Create composite image
rgb_composite_n = np.dstack((red_n, green_n, blue_n))

# Display image
plt.imshow(rgb_composite_n)

# Save image to file
matplotlib.image.imsave(f"{Path.home()}/Sentinel2_true_color.jpeg", rgb_composite_n)
print("Saved as:", outfile)

#####################################################################################################################################
#
##Added a execution timer.
#Source code: https://datatofish.com/measure-time-to-run-python-script/#:~:text=You%20may%20use%20the%20time%20module%20in%20order,%28%27Execution%20time%20in%20seconds%3A%20%27%20%2B%20str%20%28executionTime%29%29import pandas as pd
#
#####################################################################################################################################

import numpy as np
import time

startTime = time.time()

df = pd.DataFrame(np.random.randint(1,9999,size=(10000000, 1)), columns=['Random numbers'])
df['Random numbers'] = df['Random numbers'].astype(str)

executionTime = (time.time() - startTime)
print('Execution time in seconds: ' + str(executionTime))

**Comment by KanerLev** [comment]
Dear,
We realized some custom code lines in the screenshot you shared and as our support and knowledge in Python is limited and scoped with the examples provided in our documentation, unfortunately we are not able to troubleshoot your code. However we checked if the notebook provided in the documentation [here](https://documentation.dataspace.copernicus.eu/notebook-samples/geo/odata_basics.html) works smoothly, and it worked. 

Here's what we can mention:
-Although it's recommended to feed your username and password from an external file, since you mentioned that " I did enter my email and password where it says "my_email" and "my_password" ", to be able to replicate, we did the same, see attached image.
-We created a Geo Science Notebook in Jupyter and followed the document: https://documentation.dataspace.copernicus.eu/notebook-samples/geo/odata_basics.html and it worked properly.

Therefore we reckon the issue you encountered is not related to the notebook as it is provided in the documentation; it may be the custom code you added, or it may be the environment (e.g. it works with Geo Science) ...
![username_pwd](https://github.com/eu-cdse/documentation/assets/78963238/71f7cc88-125a-43d9-bd75-8ef983088ea7)
![checking_the_notebook_in_documentation](https://github.com/eu-cdse/documentation/assets/78963238/5f3d2c5a-5eab-4912-9a22-e31078ab9c34)

Please see attached for our findings.

Please note that here we aim to maintain issues that are only related to the [documentation portal](https://documentation.dataspace.copernicus.eu/Home.html).

For the issues that require user support, please [contact user support](https://helpcenter.dataspace.copernicus.eu/hc/en-gb).
