### ISSUE TITLE
Better page visualization for Data, API and Application introduction page

### ISSUE THREAD

**Issue by Pratichhya** [eu-cdse/documentation#397]
A tile or grided visualisation for better management and effective visualisation should be introduced. Such as for the pages:
https://documentation.dataspace.copernicus.eu/Data.html, https://documentation.dataspace.copernicus.eu/APIs.html, https://documentation.dataspace.copernicus.eu/Applications.html and if possible, for each Dataset page too

This can be done in two-phase:

- [x] Modify page visualization for the introductory page
- [x] Maintain Alias
- [x] Modify page visualization for data sections

**Comment by Pratichhya** [comment]
Internal comments: "If you change URL, you should create an alias pointing to the new URL, to ensure backward compatibility."

This has to be implemented for future maintainance

**Comment by KanerLev** [comment]
> Internal comments: "If you change URL, you should create an alias pointing to the new URL, to ensure backward compatibility."
> 
> This has to be implemented for future maintainance

This is satisfied over several PRs see #409 , #426 , #463, #468
