### ISSUE TITLE
Convert parcel delineation to community example

### ISSUE THREAD

**Issue by jdries** [eu-cdse/documentation#401]
This notebook:
https://github.com/openEOPlatform/parcel-delineation
Can be converted to a community example:
https://github.com/Open-EO/openeo-community-examples

Todo's:

- [x] Try to convert to ONNX (there's another example notebook that demonstrates this
- [x] See if we can simplify the UDF's
- [x] Put the ONNX model also in the github repo
- [x] Update udf signature to work on xarray.DataArray directly (should work)
- [ ] link to the new example from here: https://open-eo.github.io/openeo-python-client/udf.html#example-apply-neighborhood-with-a-udf

I would also change how we select 12 usable observations: we can use aggregate_spatial to compute a cloud % over the full aoi, or even larger, perhaps at lower resolution, to make it faster.
This gives us a set of usable dates, that we can load using filter_labels.
This approach would get rid of the first UDF.

**Comment by VictorVerhaert** [comment]
Notebook has been fully rewritten. 
Major changes:
- udf_reduce_images.py is no longer used, aggregate_spatial is used instead
- udf_segmentation.py has been adapted so that models are executed in onnxruntime env

The final vectorization does however look weird. Who has experience with this process?

**Comment by jdries** [comment]
Nice progress!

best to check with @JeroenVerstraelen for vectorization, this indeed looks like a regression. It looks as if the area outside of the processed bounds is also being vectorized, causing these shapes.

Can you also create a PR for this in the community-samples repo?

**Comment by VictorVerhaert** [comment]
Changing the type to xarray.DataArray in `apply_datacube` in `udf_segmentation` raises `OpenEoUdfException("No UDF found.") openeo.udf.OpenEoUdfException: No UDF found.` when executing. 
What is the reason we would want to change this to use xarray.DataArray directly (efficiency?)

**Comment by jdries** [comment]
These are the conditions that should be satisfied for the signature to be found:
https://github.com/Open-EO/openeo-python-client/blob/7ce92925dd9544ff116b14c0339de203f854ec27/openeo/udf/run_code.py#L184
(It's python client code, so can even be debugged locally.)

People preferred to have UDF's that do not require openeo imports, allowing them to put 'udf's' into libraries that do not come with an openEO dependency. It's also a bit more user friendly, because this wrapping/unwrapping of the dataarray makes the code slightly more complex.

**Comment by VictorVerhaert** [comment]
udf signature has been changed.

TODO before this can be a community example:
- [ ] rewrite preprocessing
- [ ] Wait for `raster_to_vector` to be fixed

Other TODO's:
- [ ] Get notebook working on CDSE (waiting for Cloudferro approval on UDF usage)
- [ ] use `scl_mask_dilation` instead of classic mapping of the SCL layer to be more in line with community examples

**Comment by VictorVerhaert** [comment]
A PR has been created: [pull request](https://github.com/Open-EO/openeo-community-examples/pull/14)

**Comment by VictorVerhaert** [comment]
Using the openeo-dev.vito backend, the raster_to_vector process now returns an expected result. It does not yet work on the production backend.

**Comment by VictorVerhaert** [comment]
Notebook works on CDSE now.
raster_to_vector now also gives correct result

**Comment by VictorVerhaert** [comment]
When changing the type to DataArray (in both udf's), the arguments name still needs to be cube. This might cause some confusion (it did with me). Perhaps we should change this in the python client code so that the argument also gets accepted as `array`. Should I create a new ticket for this?
