### ISSUE TITLE
Procedure for "message":"This request was rejected due to a violation.

### ISSUE THREAD

**Issue by Pratichhya** [eu-cdse/documentation#435]
An error is encountered when implementing UDF in openEO that fetch files within it from a different source.
Failed to parse API error response: [403] '{"status":"error","data":{"message":"This request was rejected due to a violation. Please consult with your administrator, and provide this reference ID:  12308030347893165864"}}'

This is resolved after requesting CF to allow the ID. However, users have been encountering things, and maybe we should document them somewhere on where and target them to whom.

**Comment by Slegersj** [comment]
https://github.com/eu-cdse/documentation/pull/557 merged
