### ISSUE TITLE
Notebooks are displayed with two titles

### ISSUE THREAD

**Issue by Pratichhya** [eu-cdse/documentation#440]
I'm not exactly sure why, but there seem to be two titles in every page in the notebook examples. However, there is a single title at the navigation bar on the right.

**Comment by KanerLev** [comment]
e.g. https://documentation.dataspace.copernicus.eu/notebook-samples/openeo/NDVI_Timeseries.html

**Comment by Slegersj** [comment]
It still looks good on the staging environment.
Is it perhaps a side effect of the introduction of 'the navigated path' just above the first title?

Staging
![image](https://github.com/eu-cdse/documentation/assets/124564312/c6950c4f-146b-4ed8-a996-c670c9b30f15)

**Comment by Pratichhya** [comment]
Bread-crumbs seems to be true by default in yml file

**Comment by jdries** [comment]
This indeed looks like an issue that we already solved with the old structure, but I wasn't aware that we changed it.
@Pratichhya  if you have the commit or pull request that moved notebooks, perhaps looking at the previous setup shows how we got rid of this last time?

**Comment by Pratichhya** [comment]
Hi @jdries, the new structure for the use case was a reference point to start for the support team, as discussed with them last week. Nevertheless, it still needs to be improved, including the categories. 

However, yes, we are not yet sure of the cause of the two titles, which seems to have started at some point before this new structure as seen [here](https://eu-cdse.github.io/documentation/pr-preview/pr-420/notebook-samples/openeo/NDVI_Timeseries.html). While inspecting, it gives a hint, might be caused due to quarto but not yet sure where we are working on it but the problem is we cannot replicate the issue in our local environment.

**Comment by jdries** [comment]
Did you consider the possibility that this was caused by new quarto release on januari 24?
https://quarto.org/docs/blog/posts/2024-01-24-1.4-release/

**Comment by Pratichhya** [comment]
Ahh, no, I did; thank you for the hint; I will try to check if this could also be the issue. Thank you 😃

**Comment by Pratichhya** [comment]
I assume changing the version did work. Thank you @jdries
