### ISSUE TITLE
Documentation/APIs/SentinelHub/Data/Digital Elevation Model (DEM) Data

### ISSUE THREAD

**Issue by KanerLev** [eu-cdse/documentation#513]
Documentation/APIs/SentinelHub/Data/Digital Elevation Model (DEM) Data (https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Data/DEM.html), states "For Copernicus DEM GLO-90, check the [terms](https://spacedata.copernicus.eu/documents/20123/121286/CSCDA_ESA_Mission-specific+Annex_31_Oct_22.pdf) on page 15"

![image](https://github.com/eu-cdse/documentation/assets/78963238/0613d348-e7f9-4ec0-a2d2-d3b8fafba9af)

terms hyperlink opens "Page Not Found". Can you update it with the original URL?

Note: we found a URL that seems to fit however it doesn't have "page 15" as the above text suggests: https://esa.maps.eox.at/copernicus-dem_eula.pdf

**Comment by versniksinergise** [comment]
I fixed this link and a few others that were pointing to content that does not exist anymore in this pull request: https://github.com/eu-cdse/documentation/pull/577. I am closing this issue
