### ISSUE TITLE
[IMPORTANT] sentinel-5p: invalid catalog link

### ISSUE THREAD

**Issue by jdries** [eu-cdse/documentation#548]
Unclear how this could every pass review, but links to the catalog for sentinel-5p data are simply invalid:
https://documentation.dataspace.copernicus.eu/Data/SentinelMissions/Sentinel5P.html

Example of bad link:
https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel5P/search.json?&filter=producttype:L2__CO____%20AND%20processingmode:Offline

Working link:
https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel5P/search.json?productType=L2__CO____

**Comment by KanerLev** [comment]
Solved by #564
