### ISSUE TITLE
JupyterHub kernel documentation

### ISSUE THREAD

**Issue by clausmichele** [eu-cdse/documentation#565]
During the recent [GEO-OPEN-HACK-2024](https://iiasa.ac.at/events/jun-2024/geo-open-hack-2024-big-geospatial-data-hackathon-with-open-infrastructure-and-tools) workshop I demonstrated openEO using the JupyterHub instance offered by CDSE. I have been asked where the Python environments (kernels) offered are documented, with the list of libraries and versions installed. I couldn't find it in the documentation, is it already available? If not, would it be possible to add it to the docs? Thanks!

**Comment by KanerLev** [comment]
Hi @clausmichele,
Are you looking for the list of packages that could be obtained via running the command `conda list`?

![conda_list](https://github.com/eu-cdse/documentation/assets/78963238/07d79118-a1d1-410d-a1d8-c45acde77d10)

If yes, 
-no it's not available in the documentation,
-we will raise it internally and once/if it's approved we will place it in our documentation.
If no, can you please provide more details.

**Comment by clausmichele** [comment]
@KanerLev thanks for the reply. This is a possibility, but I was wondering if the conda environment file is also publicly available (maybe here on GitHub) and can be referenced somewhere. This would allow the users to mention issues with the current environment and maybe propose new libraries to be added.
In terms of reproducibility it would be a good addition, since it would be possible to refer to a conda environment that was tested at the time of execution.

**Comment by KanerLev** [comment]
Dear Michele,

Sure. Apologies for the late coming back: we communicated your request received feedback that it's logged. Throughout the evolution of the project it may or may not be implemented. If there are any updates, it will be reflected possibly on github. 

For now please submit your suggestions to add new libraries through [Submit a request](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new) and we will communicate them to the Jupyter team.
