### ISSUE TITLE
Build-deploy documentation PR stuck in Render

### ISSUE THREAD

**Issue by Kampen1988** [eu-cdse/documentation#587]
The build-deploy of [PR #586](https://github.com/eu-cdse/documentation/pull/586) seems to [get stuck in Render](https://github.com/eu-cdse/documentation/actions/runs/10165302489/job/28144099981?pr=586) phase and fails after several hours. I restarted the job and it's been running for more than 4 hours.

![image](https://github.com/user-attachments/assets/6b2caada-2544-4e5d-afff-5f4a98e204fe)

**Comment by Kampen1988** [comment]
@KanerLev, Do you know who would be responsible for investigating the issue?

**Comment by KanerLev** [comment]
Yes, I'll ping openEO team when they are back. 
In the meantime I'll look for a solution.

**Comment by KanerLev** [comment]
@Kampen1988 Ping is acknowledged. Expecting progress/solution soon.

**Comment by Kampen1988** [comment]
The rendering seems to be fixed.
