### ISSUE TITLE
CDSE Bursts catalog

### ISSUE THREAD

**Issue by clausmichele** [eu-cdse/documentation#655]
Dear CDSE team. Following the great news about the [new Sentinel-1 bursts catalog](https://dataspace.copernicus.eu/news/2024-11-22-sentinel-1-slc-bursts-are-available-cdse) we started to perform some investigation on how to use it, but there are some points to be clarified.

It seems that the Sentinel-1 SLC .zip content has been uploaded on the object storage and now it's possible to access the files independently, which is good. However, the smallest part of a Sentinel-1 acquisition which is possible to access/download is a geoTIFF containing a full Sentinel-1 Subswath, which consist in many bursts, but it's not possible to access directly to a single burst. Hence, it seems more a Subswath catalog rather than a Burst catalog.

Additionally, the text in the [documentation](https://github.com/eu-cdse/documentation/blob/publish/APIs/Sentinel-1%20SLC%20Burst.qmd) contain some mistakes, for instance:

> A burst cycle comprises three consecutive **bursts** in IW mode (IW1, IW2, IW3)

but it should be 

> A burst cycle comprises three consecutive **subswaths** in IW mode (IW1, IW2, IW3)

**Comment by KanerLev** [comment]
Dear @clausmichele, 

Thank you!  

Per object storage remark: Please note that this repository (https://github.com/eu-cdse/documentation) and its issue tracker are purely for development and maintenance of the documentation. Accordingly, if you can [Submit a request](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new) we can forward it to the corresponding / content providing partner for their feedback. Thank you for your cooperation.

Per 'mistakes': as mentioned mistake is not just a typo and there is a technical aspect to it (i.e. preferred terminology: burst or subswath) we are going to consult it to the second line support / expert teams for their feedback. If it's approved, we will update the [Sentinel-1 SLC Bursts](https://documentation.dataspace.copernicus.eu/APIs/Sentinel-1%20SLC%20Burst.html) as soon as possible.

Kind regards,
CDSE Support Team

**Comment by KanerLev** [comment]
Hi @clausmichele, 

At the moment it is not known to us whether the terminology change "from burst to subswath" is accepted by the corresponding technical team. We forwarded your recommendation to the corresponding team, and are waiting for feedback.

If changed, it will be reflected in [Sentinel-1 SLC Bursts](https://documentation.dataspace.copernicus.eu/APIs/Sentinel-1%20SLC%20Burst.html ), 
We can keep the issue open until we hear a feedback.

Any other feedback / suggestions please share.

**Comment by j-musial** [comment]
@KanerLev we do confirm the change. 

@clausmichele thanks!

**Comment by KanerLev** [comment]
Thanks for the update: @j-musial (https://github.com/eu-cdse/documentation/commit/7463273dc4fe22640b94bd906b52abc955ffd978)

Accordingly we are closing the issue.
